[package]

name = "augeas"
version = "0.0.1"
authors = ["panicbit <panicbit@users.noreply.github.com>"]

[dependencies]
libc = "*"

[dependencies.augeas_sys]
git = "https://github.com/panicbit/augeas_sys"
