[package]
name = "augeas_sys"
version = "0.0.1"
authors = ["panicbit <panicbit.dev@gmail.com>"]
description = "Low level bindings for augeas"
license = "MIT"
keywords = ["augeas", "bindings"]
repository = "https://github.com/panicbit/augeas_sys"

[dependencies]
libc = "*"
